platform :ios, '11.0'

target 'ETicket' do
pod 'AFNetworking'
pod 'Masonry'
pod 'MJRefresh'
pod 'ReactiveCocoa','~>2.5'
pod 'BlocksKit'
pod 'JMHoledView'
pod 'SQLitePersistentObjects'
pod 'WYPopoverController'
pod 'EDColor'
pod 'TPKeyboardAvoiding'
pod 'Base64', '~> 1.1.2'
pod 'ShareSDK3'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKExtension'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
pod 'ShareSDK3/ShareSDKPlatforms/Facebook'
pod 'Mantle'
pod 'SDWebImage','3.8.2'
pod 'YYImage'
pod 'MBProgressHUD','~> 1.0.0'
pod 'KMNavigationBarTransition'
pod 'TTTAttributedLabel'
pod 'YLGIFImage'
pod 'QQ_XGPush'
pod 'SCLAlertView-Objective-C'
end
